name: macOS Release Tracker

on:
  schedule:
    - cron: '* */8 * * *' # every 8 hours
  workflow_dispatch:

jobs:
  check-macos-releases:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ungive/mediaremote-adapter
      APP_ID: 1425660
      INSTALLATION_ID: 71955299
      ISSUE_TITLE_FORMAT: Test on {}
      ISSUE_LABELS: automated issue,macOS compatibility,help wanted
      APP_PRIVATE_KEY: ${{ secrets.MACOS_RELEASE_TRACKER_APP_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Initialize workflow submodule
        run: |
          git submodule init .github/workflows/macos-release-tracker
          git submodule update .github/workflows/macos-release-tracker

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/macos-release-tracker/requirements.txt

      - name: Run script
        run: |
          python .github/workflows/macos-release-tracker/runner.py
